# Form implementation generated from reading ui file 'dialog_header.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_header(object):
    def setupUi(self, dialog_header):
        dialog_header.setObjectName("dialog_header")
        dialog_header.resize(400, 259)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_header)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line_frame = QtWidgets.QLineEdit(parent=dialog_header)
        self.line_frame.setGeometry(QtCore.QRect(200, 100, 113, 25))
        self.line_frame.setObjectName("line_frame")
        self.label_10 = QtWidgets.QLabel(parent=dialog_header)
        self.label_10.setGeometry(QtCore.QRect(90, 100, 100, 25))
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(parent=dialog_header)
        self.label_3.setGeometry(QtCore.QRect(90, 40, 100, 25))
        self.label_3.setObjectName("label_3")
        self.line_offset = QtWidgets.QLineEdit(parent=dialog_header)
        self.line_offset.setGeometry(QtCore.QRect(200, 40, 113, 25))
        self.line_offset.setObjectName("line_offset")

        self.retranslateUi(dialog_header)
        self.buttonBox.accepted.connect(dialog_header.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_header.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_header)

    def retranslateUi(self, dialog_header):
        _translate = QtCore.QCoreApplication.translate
        dialog_header.setWindowTitle(_translate("dialog_header", "Dialog"))
        self.label_10.setText(_translate("dialog_header", "frame_id"))
        self.label_3.setText(_translate("dialog_header", "time_offset:"))
