# Form implementation generated from reading ui file 'dialog_path.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_path(object):
    def setupUi(self, dialog_path):
        dialog_path.setObjectName("dialog_path")
        dialog_path.resize(1071, 821)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_path)
        self.buttonBox.setGeometry(QtCore.QRect(550, 770, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_frame_id = QtWidgets.QLabel(parent=dialog_path)
        self.label_frame_id.setGeometry(QtCore.QRect(120, 50, 67, 17))
        self.label_frame_id.setObjectName("label_frame_id")
        self.line_frame_id = QtWidgets.QLineEdit(parent=dialog_path)
        self.line_frame_id.setGeometry(QtCore.QRect(200, 45, 150, 30))
        self.line_frame_id.setObjectName("line_frame_id")
        self.btn_add_row = QtWidgets.QPushButton(parent=dialog_path)
        self.btn_add_row.setGeometry(QtCore.QRect(110, 120, 120, 30))
        self.btn_add_row.setObjectName("btn_add_row")
        self.btn_del_row = QtWidgets.QPushButton(parent=dialog_path)
        self.btn_del_row.setGeometry(QtCore.QRect(280, 120, 120, 30))
        self.btn_del_row.setObjectName("btn_del_row")
        self.scrollArea = QtWidgets.QScrollArea(parent=dialog_path)
        self.scrollArea.setGeometry(QtCore.QRect(100, 200, 951, 481))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 947, 477))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget = QtWidgets.QWidget(parent=dialog_path)
        self.widget.setGeometry(QtCore.QRect(100, 170, 731, 19))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)

        self.retranslateUi(dialog_path)
        self.buttonBox.accepted.connect(dialog_path.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_path.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_path)

    def retranslateUi(self, dialog_path):
        _translate = QtCore.QCoreApplication.translate
        dialog_path.setWindowTitle(_translate("dialog_path", "Dialog"))
        self.label_frame_id.setText(_translate("dialog_path", "frame_id:"))
        self.btn_add_row.setText(_translate("dialog_path", "+添加行"))
        self.btn_del_row.setText(_translate("dialog_path", "- 删除最后一行"))
        self.label.setText(_translate("dialog_path", "t_offset"))
        self.label_2.setText(_translate("dialog_path", "pos.x"))
        self.label_3.setText(_translate("dialog_path", "pos.y"))
        self.label_4.setText(_translate("dialog_path", "pos.z"))
        self.label_5.setText(_translate("dialog_path", "ori.x"))
        self.label_6.setText(_translate("dialog_path", "ori.y"))
        self.label_7.setText(_translate("dialog_path", "ori.z"))
        self.label_8.setText(_translate("dialog_path", "ori.w"))
