# Form implementation generated from reading ui file 'dialog_posestamped.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_posestamped(object):
    def setupUi(self, dialog_posestamped):
        dialog_posestamped.setObjectName("dialog_posestamped")
        dialog_posestamped.resize(400, 500)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_posestamped)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 450, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_6 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_6.setGeometry(QtCore.QRect(90, 200, 75, 25))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_4.setGeometry(QtCore.QRect(90, 250, 100, 25))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 200, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit.setGeometry(QtCore.QRect(200, 100, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 300, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 350, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_9.setGeometry(QtCore.QRect(90, 150, 75, 25))
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 75, 25))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_5.setGeometry(QtCore.QRect(90, 300, 100, 25))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_7.setGeometry(QtCore.QRect(90, 350, 100, 25))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 250, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 150, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 400, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_8.setGeometry(QtCore.QRect(90, 400, 100, 25))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_3.setGeometry(QtCore.QRect(90, 20, 100, 25))
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(parent=dialog_posestamped)
        self.label_10.setGeometry(QtCore.QRect(90, 60, 100, 25))
        self.label_10.setObjectName("label_10")
        self.line_offset = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.line_offset.setGeometry(QtCore.QRect(200, 20, 113, 25))
        self.line_offset.setObjectName("line_offset")
        self.line_frame = QtWidgets.QLineEdit(parent=dialog_posestamped)
        self.line_frame.setGeometry(QtCore.QRect(200, 60, 113, 25))
        self.line_frame.setObjectName("line_frame")

        self.retranslateUi(dialog_posestamped)
        self.buttonBox.accepted.connect(dialog_posestamped.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_posestamped.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_posestamped)

    def retranslateUi(self, dialog_posestamped):
        _translate = QtCore.QCoreApplication.translate
        dialog_posestamped.setWindowTitle(_translate("dialog_posestamped", "Dialog"))
        self.label_6.setText(_translate("dialog_posestamped", "position.z:"))
        self.label_4.setText(_translate("dialog_posestamped", "orientation.x:"))
        self.label_9.setText(_translate("dialog_posestamped", "position.y:"))
        self.label_2.setText(_translate("dialog_posestamped", "position.x:"))
        self.label_5.setText(_translate("dialog_posestamped", "orientation.y:"))
        self.label_7.setText(_translate("dialog_posestamped", "orientation.z:"))
        self.label_8.setText(_translate("dialog_posestamped", "orientation.w:"))
        self.label_3.setText(_translate("dialog_posestamped", "time_offset:"))
        self.label_10.setText(_translate("dialog_posestamped", "frame_id:"))
