# Form implementation generated from reading ui file './dialog_pose.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_pose(object):
    def setupUi(self, dialog_pose):
        dialog_pose.setObjectName("dialog_pose")
        dialog_pose.resize(301, 432)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_pose)
        self.buttonBox.setGeometry(QtCore.QRect(50, 380, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_4 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 100, 25))
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 230, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_2.setGeometry(QtCore.QRect(46, 30, 75, 25))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 80, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 100, 25))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_6.setGeometry(QtCore.QRect(50, 130, 75, 25))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 280, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 130, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 180, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_7.setGeometry(QtCore.QRect(50, 280, 100, 25))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit.setGeometry(QtCore.QRect(160, 30, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=dialog_pose)
        self.lineEdit_7.setGeometry(QtCore.QRect(160, 330, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_8.setGeometry(QtCore.QRect(50, 330, 100, 25))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=dialog_pose)
        self.label_9.setGeometry(QtCore.QRect(50, 80, 75, 25))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(dialog_pose)
        self.buttonBox.accepted.connect(dialog_pose.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_pose.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_pose)

    def retranslateUi(self, dialog_pose):
        _translate = QtCore.QCoreApplication.translate
        dialog_pose.setWindowTitle(_translate("dialog_pose", "Dialog"))
        self.label_4.setText(_translate("dialog_pose", "orientation.x:"))
        self.label_2.setText(_translate("dialog_pose", "position.x:"))
        self.label_5.setText(_translate("dialog_pose", "orientation.y:"))
        self.label_6.setText(_translate("dialog_pose", "position.z:"))
        self.label_7.setText(_translate("dialog_pose", "orientation.z:"))
        self.label_8.setText(_translate("dialog_pose", "orientation.w:"))
        self.label_9.setText(_translate("dialog_pose", "position.y:"))
