# Form implementation generated from reading ui file 'dialog_float32.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_float32(object):
    def setupUi(self, dialog_float32):
        dialog_float32.setObjectName("dialog_float32")
        dialog_float32.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_float32)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=dialog_float32)
        self.label.setGeometry(QtCore.QRect(60, 60, 67, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=dialog_float32)
        self.textEdit.setGeometry(QtCore.QRect(100, 60, 241, 70))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(dialog_float32)
        self.buttonBox.accepted.connect(dialog_float32.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_float32.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_float32)

    def retranslateUi(self, dialog_float32):
        _translate = QtCore.QCoreApplication.translate
        dialog_float32.setWindowTitle(_translate("dialog_float32", "Dialog"))
        self.label.setText(_translate("dialog_float32", "数据:"))
