# Form implementation generated from reading ui file 'dialog_odometry.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_odometry(object):
    def setupUi(self, dialog_odometry):
        dialog_odometry.setObjectName("dialog_odometry")
        dialog_odometry.resize(400, 561)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_odometry)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 510, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line_frame = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.line_frame.setGeometry(QtCore.QRect(200, 70, 113, 25))
        self.line_frame.setObjectName("line_frame")
        self.line_offset = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.line_offset.setGeometry(QtCore.QRect(200, 30, 113, 25))
        self.line_offset.setObjectName("line_offset")
        self.label_2 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 75, 25))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 310, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_7.setGeometry(QtCore.QRect(90, 410, 100, 25))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_5.setGeometry(QtCore.QRect(90, 360, 100, 25))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 260, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 410, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit.setGeometry(QtCore.QRect(200, 160, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_9.setGeometry(QtCore.QRect(90, 210, 75, 25))
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 360, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 460, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_6 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_6.setGeometry(QtCore.QRect(90, 260, 75, 25))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 210, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_3.setGeometry(QtCore.QRect(90, 30, 100, 25))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_8.setGeometry(QtCore.QRect(90, 460, 100, 25))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_4.setGeometry(QtCore.QRect(90, 310, 100, 25))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_10.setGeometry(QtCore.QRect(90, 70, 100, 25))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=dialog_odometry)
        self.label_11.setGeometry(QtCore.QRect(90, 110, 110, 25))
        self.label_11.setObjectName("label_11")
        self.line_frame_2 = QtWidgets.QLineEdit(parent=dialog_odometry)
        self.line_frame_2.setGeometry(QtCore.QRect(200, 110, 113, 25))
        self.line_frame_2.setObjectName("line_frame_2")

        self.retranslateUi(dialog_odometry)
        self.buttonBox.accepted.connect(dialog_odometry.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_odometry.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_odometry)

    def retranslateUi(self, dialog_odometry):
        _translate = QtCore.QCoreApplication.translate
        dialog_odometry.setWindowTitle(_translate("dialog_odometry", "Dialog"))
        self.label_2.setText(_translate("dialog_odometry", "position.x:"))
        self.label_7.setText(_translate("dialog_odometry", "orientation.z:"))
        self.label_5.setText(_translate("dialog_odometry", "orientation.y:"))
        self.label_9.setText(_translate("dialog_odometry", "position.y:"))
        self.label_6.setText(_translate("dialog_odometry", "position.z:"))
        self.label_3.setText(_translate("dialog_odometry", "time_offset:"))
        self.label_8.setText(_translate("dialog_odometry", "orientation.w:"))
        self.label_4.setText(_translate("dialog_odometry", "orientation.x:"))
        self.label_10.setText(_translate("dialog_odometry", "frame_id:"))
        self.label_11.setText(_translate("dialog_odometry", "child_frame_id:"))
