# Form implementation generated from reading ui file './dialog_bool.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_bool(object):
    def setupUi(self, dialog_bool):
        dialog_bool.setObjectName("dialog_bool")
        dialog_bool.resize(186, 220)
        self.btn_true = QtWidgets.QPushButton(parent=dialog_bool)
        self.btn_true.setGeometry(QtCore.QRect(60, 40, 70, 50))
        self.btn_true.setObjectName("btn_true")
        self.btn_false = QtWidgets.QPushButton(parent=dialog_bool)
        self.btn_false.setGeometry(QtCore.QRect(60, 130, 70, 50))
        self.btn_false.setObjectName("btn_false")

        self.retranslateUi(dialog_bool)
        QtCore.QMetaObject.connectSlotsByName(dialog_bool)

    def retranslateUi(self, dialog_bool):
        _translate = QtCore.QCoreApplication.translate
        dialog_bool.setWindowTitle(_translate("dialog_bool", "Dialog"))
        self.btn_true.setText(_translate("dialog_bool", "True"))
        self.btn_false.setText(_translate("dialog_bool", "False"))
