# Form implementation generated from reading ui file './dialog_twist.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_twist(object):
    def setupUi(self, dialog_twist):
        dialog_twist.setObjectName("dialog_twist")
        dialog_twist.resize(261, 365)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_twist)
        self.buttonBox.setGeometry(QtCore.QRect(20, 320, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(parent=dialog_twist)
        self.lineEdit.setGeometry(QtCore.QRect(110, 20, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=dialog_twist)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 270, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=dialog_twist)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 170, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(parent=dialog_twist)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 67, 25))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=dialog_twist)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 70, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(parent=dialog_twist)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 67, 25))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=dialog_twist)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 67, 25))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=dialog_twist)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 67, 25))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=dialog_twist)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 120, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(parent=dialog_twist)
        self.label.setGeometry(QtCore.QRect(20, 20, 67, 25))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=dialog_twist)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 67, 25))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=dialog_twist)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 220, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.retranslateUi(dialog_twist)
        self.buttonBox.accepted.connect(dialog_twist.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_twist.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_twist)

    def retranslateUi(self, dialog_twist):
        _translate = QtCore.QCoreApplication.translate
        dialog_twist.setWindowTitle(_translate("dialog_twist", "Dialog"))
        self.label_3.setText(_translate("dialog_twist", "线速度z:"))
        self.label_5.setText(_translate("dialog_twist", "角速度y:"))
        self.label_2.setText(_translate("dialog_twist", "线速度y:"))
        self.label_4.setText(_translate("dialog_twist", "角速度x:"))
        self.label.setText(_translate("dialog_twist", "线速度x:"))
        self.label_6.setText(_translate("dialog_twist", "角速度z:"))
