# Form implementation generated from reading ui file 'dialog_int16.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_int16(object):
    def setupUi(self, dialog_int16):
        dialog_int16.setObjectName("dialog_int16")
        dialog_int16.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_int16)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=dialog_int16)
        self.label.setGeometry(QtCore.QRect(60, 40, 67, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=dialog_int16)
        self.textEdit.setGeometry(QtCore.QRect(100, 40, 241, 70))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(dialog_int16)
        self.buttonBox.accepted.connect(dialog_int16.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_int16.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_int16)

    def retranslateUi(self, dialog_int16):
        _translate = QtCore.QCoreApplication.translate
        dialog_int16.setWindowTitle(_translate("dialog_int16", "Dialog"))
        self.label.setText(_translate("dialog_int16", "数据:"))
