# Form implementation generated from reading ui file './dialog_string.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_string(object):
    def setupUi(self, dialog_string):
        dialog_string.setObjectName("dialog_string")
        dialog_string.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_string)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=dialog_string)
        self.label.setGeometry(QtCore.QRect(40, 40, 67, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=dialog_string)
        self.textEdit.setGeometry(QtCore.QRect(80, 40, 241, 70))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(dialog_string)
        self.buttonBox.accepted.connect(dialog_string.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_string.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_string)

    def retranslateUi(self, dialog_string):
        _translate = QtCore.QCoreApplication.translate
        dialog_string.setWindowTitle(_translate("dialog_string", "Dialog"))
        self.label.setText(_translate("dialog_string", "数据:"))
